permalink: /:year-:month-:day/:title/
title: SemiTransparent 主题
email: zzy8200@gmail.com
description: 同款WordPress主题的Jekyll实现
hgimgcount: 3 # Number of the possible top images, images must be jpg and 1000 * 288. Put images in static/hgimg folder and rename them as 1.jpg, 2.jpg...
url: https://zeruniverse.github.io/semitransparent-jekyll-theme

paginate: 5
paginate_path: "/page:num/"

navigation:
  - text: RSS
    url: /feed.xml
  - text: GitHub
    url: https://github.com/zeruniverse/semitransparent-jekyll-theme
  - text: 作者
    url: http://zzeyu.com/

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"

gems:
  - jekyll-paginate
  
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
